print('Hello world!')
print('What is ur name?')
myName = input()
print('It is good to meet u, ' + myName)
print('The length of ur name is:')
print(len(myName))
print('What is ur age?')
myAge = input()
print('U will be ' + str(int(myAge) + 1) + ' in a year.')